// <auto-generated />
using System;
using Lagerverwaltung.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lagerverwaltung.Migrations
{
    [DbContext(typeof(LagerDbContext))]
    [Migration("20250129113912_mssql.local_migration_580")]
    partial class mssqllocal_migration_580
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lagerverwaltung.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtikelId"));

                    b.Property<string>("Artikelname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LagerplatzId")
                        .HasColumnType("int");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<decimal>("PreisProEinheit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArtikelId");

                    b.HasIndex("LagerplatzId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("Lagerverwaltung.Models.Benutzer", b =>
                {
                    b.Property<int>("BenutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenutzerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenutzerId");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("Lagerverwaltung.Models.Lagerplatz", b =>
                {
                    b.Property<int>("LagerplatzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LagerplatzId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LagerplatzId");

                    b.ToTable("Lagerplatz");
                });

            modelBuilder.Entity("Lagerverwaltung.Models.Logbuch", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Artikelnummer")
                        .HasColumnType("int");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("Logbuch");
                });

            modelBuilder.Entity("Lagerverwaltung.Models.Artikel", b =>
                {
                    b.HasOne("Lagerverwaltung.Models.Lagerplatz", "Lagerplatz")
                        .WithMany()
                        .HasForeignKey("LagerplatzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lagerplatz");
                });
#pragma warning restore 612, 618
        }
    }
}
